### ISSUE TITLE
How to change the background color or set the background image for all bottomsheets?

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [arthur3486/bottomsheets#1]
Is it possible to change the background color or set the background image for all bottomsheets?
I don't want to use the custom view and I want the other variants to be customized

**Comment by arthur3486** [comment]
HI @Morteza-Rastgoo !

You can change the bottom sheet background color by providing a custom configuration during the creation of the bottom sheet (See: [`Action Picker Config`](https://github.com/arthur3486/bottomsheets/blob/master/bottomsheets-sheets/src/main/java/com/arthurivanets/bottomsheets/sheets/config/Config.java) and [`Base Config`](https://github.com/arthur3486/bottomsheets/blob/master/bottomsheets-core/src/main/java/com/arthurivanets/bottomsheets/config/Config.java)).
